/*
    Creates base database for $(database)
*/
USE [master]

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'$(database)')
DROP DATABASE [$(database)]

USE [master]

CREATE DATABASE [$(database)]
ALTER DATABASE [$(database)] SET COMPATIBILITY_LEVEL = 100

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [$(database)].[dbo].[sp_fulltext_database] @action = 'enable'
END

ALTER DATABASE [$(database)] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [$(database)] SET ANSI_NULLS OFF 
ALTER DATABASE [$(database)] SET ANSI_PADDING OFF 
ALTER DATABASE [$(database)] SET ANSI_WARNINGS OFF 
ALTER DATABASE [$(database)] SET ARITHABORT OFF 
ALTER DATABASE [$(database)] SET AUTO_CLOSE OFF 
ALTER DATABASE [$(database)] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [$(database)] SET AUTO_SHRINK OFF 
ALTER DATABASE [$(database)] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [$(database)] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [$(database)] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [$(database)] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [$(database)] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [$(database)] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [$(database)] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [$(database)] SET  DISABLE_BROKER 
ALTER DATABASE [$(database)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [$(database)] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [$(database)] SET TRUSTWORTHY OFF 
ALTER DATABASE [$(database)] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [$(database)] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [$(database)] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [$(database)] SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE [$(database)] SET  READ_WRITE 
ALTER DATABASE [$(database)] SET RECOVERY FULL 
ALTER DATABASE [$(database)] SET  MULTI_USER 
ALTER DATABASE [$(database)] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [$(database)] SET DB_CHAINING OFF

GO